# Generated by Django 4.2.7 on 2023-12-19 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
